export interface ToolData {
  id: string;
  name: string;
  description: string;
  icon: string;
  route: string;
  category: 'image' | 'pdf';
  keywords: string[];
  relatedTools: string[];
  faq: { question: string; answer: string }[];
  metaTitle: string;
  metaDescription: string;
}

export const imageTools: ToolData[] = [
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    description: 'Compress images online for free. Reduce image file size without losing quality.',
    icon: '🗜️',
    route: '/tools/image-compressor',
    category: 'image',
    keywords: ['image compressor online', 'compress image free', 'reduce image size', 'image optimizer'],
    relatedTools: ['image-resizer', 'jpg-to-png', 'image-to-webp'],
    faq: [
      { question: 'How does image compression work?', answer: 'Our tool uses canvas-based compression to reduce image file size by adjusting quality settings while maintaining visual fidelity.' },
      { question: 'What image formats are supported?', answer: 'We support JPG, PNG, WebP, and most common image formats.' },
      { question: 'Is there a file size limit?', answer: 'You can compress images up to 50MB in size directly in your browser.' },
      { question: 'Is my image data safe?', answer: 'Yes! All processing happens locally in your browser. Your images are never uploaded to any server.' },
    ],
    metaTitle: 'Free Image Compressor Online - Reduce Image Size Without Quality Loss',
    metaDescription: 'Compress images online for free. Reduce JPG, PNG, WebP file size without losing quality. Fast, secure, no upload required.',
  },
  {
    id: 'image-resizer',
    name: 'Image Resizer',
    description: 'Resize images online to any dimension. Free image resizing tool.',
    icon: '📐',
    route: '/tools/image-resizer',
    category: 'image',
    keywords: ['resize image online free', 'image resizer', 'change image dimensions', 'scale image'],
    relatedTools: ['image-compressor', 'image-cropper', 'jpg-to-png'],
    faq: [
      { question: 'Can I resize to custom dimensions?', answer: 'Yes, you can enter any custom width and height values.' },
      { question: 'Will resizing affect image quality?', answer: 'Enlarging images may reduce quality. Reducing size generally maintains good quality.' },
      { question: 'Can I maintain aspect ratio?', answer: 'Yes, enable the "Lock Aspect Ratio" option to maintain proportions.' },
      { question: 'What formats can I resize?', answer: 'JPG, PNG, WebP, GIF, and most common image formats.' },
    ],
    metaTitle: 'Free Image Resizer Online - Resize Images to Any Dimension',
    metaDescription: 'Resize images online for free. Change image dimensions, scale photos, and resize pictures to any size. Fast and easy image resizer.',
  },
  {
    id: 'jpg-to-png',
    name: 'JPG to PNG',
    description: 'Convert JPG images to PNG format online for free. Lossless conversion.',
    icon: '🔄',
    route: '/tools/jpg-to-png',
    category: 'image',
    keywords: ['jpg to png converter', 'convert jpg to png free', 'jpeg to png online'],
    relatedTools: ['png-to-jpg', 'image-to-webp', 'image-compressor'],
    faq: [
      { question: 'Why convert JPG to PNG?', answer: 'PNG supports transparency and lossless compression, making it ideal for logos, graphics, and images requiring transparency.' },
      { question: 'Will I lose quality converting JPG to PNG?', answer: 'No, PNG is a lossless format. The conversion preserves all visual quality.' },
      { question: 'Can I convert multiple files?', answer: 'Currently, you can convert one file at a time for best results.' },
      { question: 'Is the conversion free?', answer: 'Yes, completely free with no limits.' },
    ],
    metaTitle: 'JPG to PNG Converter - Free Online JPG to PNG Conversion',
    metaDescription: 'Convert JPG to PNG online for free. Fast, lossless JPG to PNG conversion. No signup required. Convert JPEG images to PNG format instantly.',
  },
  {
    id: 'png-to-jpg',
    name: 'PNG to JPG',
    description: 'Convert PNG images to JPG format online. Reduce file size with PNG to JPG conversion.',
    icon: '🔃',
    route: '/tools/png-to-jpg',
    category: 'image',
    keywords: ['png to jpg converter', 'convert png to jpg free', 'png to jpeg online'],
    relatedTools: ['jpg-to-png', 'image-compressor', 'image-to-webp'],
    faq: [
      { question: 'Why convert PNG to JPG?', answer: 'JPG files are smaller than PNG, making them better for web use and sharing.' },
      { question: 'Will I lose transparency?', answer: 'Yes, JPG does not support transparency. Transparent areas will be filled with white.' },
      { question: 'What quality setting should I use?', answer: 'For web use, 80-90% quality provides a good balance of size and quality.' },
      { question: 'Is this tool free?', answer: 'Yes, completely free with no watermarks.' },
    ],
    metaTitle: 'PNG to JPG Converter - Free Online PNG to JPG Conversion',
    metaDescription: 'Convert PNG to JPG online for free. Reduce file size by converting PNG images to JPG format. Fast, free, no watermarks.',
  },
  {
    id: 'image-cropper',
    name: 'Image Cropper',
    description: 'Crop images online for free. Select any area and crop your image instantly.',
    icon: '✂️',
    route: '/tools/image-cropper',
    category: 'image',
    keywords: ['image cropper online', 'crop image free', 'crop photo online', 'image crop tool'],
    relatedTools: ['image-resizer', 'image-rotator', 'image-compressor'],
    faq: [
      { question: 'How do I crop an image?', answer: 'Upload your image, drag to select the crop area, then click "Crop Image" to download.' },
      { question: 'Can I crop to specific dimensions?', answer: 'Yes, you can enter exact pixel dimensions for the crop area.' },
      { question: 'What formats are supported?', answer: 'JPG, PNG, WebP, and most common image formats.' },
      { question: 'Is my image uploaded to a server?', answer: 'No, all cropping happens locally in your browser.' },
    ],
    metaTitle: 'Free Image Cropper Online - Crop Images Instantly',
    metaDescription: 'Crop images online for free. Easy drag-to-crop interface. Crop photos to any size or dimension. No signup, no watermarks.',
  },
  {
    id: 'image-rotator',
    name: 'Image Rotator',
    description: 'Rotate images online for free. Rotate photos 90, 180, or 270 degrees.',
    icon: '🔁',
    route: '/tools/image-rotator',
    category: 'image',
    keywords: ['rotate image online', 'image rotator free', 'rotate photo online', 'flip image'],
    relatedTools: ['image-cropper', 'image-resizer', 'image-compressor'],
    faq: [
      { question: 'Can I rotate by custom angles?', answer: 'You can rotate by 90, 180, or 270 degrees, or flip horizontally/vertically.' },
      { question: 'Will rotation affect image quality?', answer: 'No, rotation is lossless and does not affect image quality.' },
      { question: 'Can I flip images?', answer: 'Yes, you can flip images horizontally or vertically.' },
      { question: 'What formats are supported?', answer: 'All common image formats including JPG, PNG, and WebP.' },
    ],
    metaTitle: 'Free Image Rotator Online - Rotate Images 90, 180, 270 Degrees',
    metaDescription: 'Rotate images online for free. Rotate photos 90, 180, or 270 degrees. Flip images horizontally or vertically. Fast and free.',
  },
  {
    id: 'image-to-webp',
    name: 'Image to WebP',
    description: 'Convert images to WebP format online. Smaller file sizes with WebP.',
    icon: '🌐',
    route: '/tools/image-to-webp',
    category: 'image',
    keywords: ['image to webp converter', 'convert to webp free', 'jpg to webp', 'png to webp'],
    relatedTools: ['webp-to-jpg', 'image-compressor', 'jpg-to-png'],
    faq: [
      { question: 'What is WebP format?', answer: 'WebP is a modern image format by Google that provides superior compression for web images.' },
      { question: 'How much smaller are WebP files?', answer: 'WebP files are typically 25-35% smaller than JPEG and 26% smaller than PNG.' },
      { question: 'Do all browsers support WebP?', answer: 'Yes, all modern browsers including Chrome, Firefox, Safari, and Edge support WebP.' },
      { question: 'Can I convert any image to WebP?', answer: 'Yes, you can convert JPG, PNG, GIF, and other formats to WebP.' },
    ],
    metaTitle: 'Image to WebP Converter - Free Online WebP Conversion Tool',
    metaDescription: 'Convert images to WebP format online for free. Reduce file size with WebP. Convert JPG, PNG to WebP. Fast, free, no signup.',
  },
  {
    id: 'webp-to-jpg',
    name: 'WebP to JPG',
    description: 'Convert WebP images to JPG format online for free. Easy WebP to JPEG conversion.',
    icon: '↩️',
    route: '/tools/webp-to-jpg',
    category: 'image',
    keywords: ['webp to jpg converter', 'convert webp to jpg free', 'webp to jpeg online'],
    relatedTools: ['image-to-webp', 'png-to-jpg', 'image-compressor'],
    faq: [
      { question: 'Why convert WebP to JPG?', answer: 'JPG has wider compatibility with older software and devices that may not support WebP.' },
      { question: 'Will I lose quality?', answer: 'Minimal quality loss occurs during conversion. You can adjust the quality setting.' },
      { question: 'Is the conversion free?', answer: 'Yes, completely free with no limits.' },
      { question: 'Can I batch convert WebP files?', answer: 'Currently one file at a time for best quality results.' },
    ],
    metaTitle: 'WebP to JPG Converter - Free Online WebP to JPEG Conversion',
    metaDescription: 'Convert WebP to JPG online for free. Easy WebP to JPEG conversion. No signup required. Download converted images instantly.',
  },
  {
    id: 'background-remover',
    name: 'Background Remover',
    description: 'Remove image background online for free. Basic background removal tool.',
    icon: '🎭',
    route: '/tools/background-remover',
    category: 'image',
    keywords: ['remove background online free', 'background remover', 'remove image background', 'transparent background'],
    relatedTools: ['image-cropper', 'image-compressor', 'png-to-jpg'],
    faq: [
      { question: 'How does background removal work?', answer: 'Our tool uses color-based detection to identify and remove solid or near-solid background colors.' },
      { question: 'What backgrounds work best?', answer: 'Solid color backgrounds (white, green, blue) work best for accurate removal.' },
      { question: 'What format is the output?', answer: 'Output is PNG format to preserve transparency.' },
      { question: 'Is this AI-powered?', answer: 'This is a basic color-based removal tool. For complex backgrounds, professional AI tools may work better.' },
    ],
    metaTitle: 'Free Background Remover Online - Remove Image Background',
    metaDescription: 'Remove image background online for free. Basic background removal tool. Works best with solid color backgrounds. Download as transparent PNG.',
  },
  {
    id: 'image-metadata-viewer',
    name: 'Image Metadata Viewer',
    description: 'View image EXIF data and metadata online. Check image properties and information.',
    icon: '🔍',
    route: '/tools/image-metadata-viewer',
    category: 'image',
    keywords: ['image metadata viewer', 'exif data viewer', 'image properties', 'photo metadata'],
    relatedTools: ['image-compressor', 'image-resizer', 'image-rotator'],
    faq: [
      { question: 'What metadata can I view?', answer: 'File name, size, dimensions, format, color depth, and basic EXIF data.' },
      { question: 'Is my image uploaded?', answer: 'No, all metadata extraction happens locally in your browser.' },
      { question: 'What image formats are supported?', answer: 'JPG, PNG, WebP, GIF, and most common image formats.' },
      { question: 'Can I edit metadata?', answer: 'This tool is for viewing only. Editing metadata requires specialized software.' },
    ],
    metaTitle: 'Image Metadata Viewer - View EXIF Data & Image Properties Online',
    metaDescription: 'View image metadata and EXIF data online for free. Check image dimensions, file size, format, and properties. No upload required.',
  },
];

export const pdfTools: ToolData[] = [
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert PDF to Word document online. Extract text from PDF files.',
    icon: '📝',
    route: '/tools/pdf-to-word',
    category: 'pdf',
    keywords: ['pdf to word converter', 'convert pdf to word free', 'pdf to docx online'],
    relatedTools: ['word-to-pdf', 'pdf-compressor', 'pdf-merge'],
    faq: [
      { question: 'How accurate is PDF to Word conversion?', answer: 'Text extraction is accurate for text-based PDFs. Scanned PDFs may have limited accuracy.' },
      { question: 'What format is the output?', answer: 'Text is extracted and provided as a downloadable text file.' },
      { question: 'Can I convert scanned PDFs?', answer: 'Scanned PDFs require OCR technology. This tool works best with text-based PDFs.' },
      { question: 'Is there a page limit?', answer: 'No page limit for text extraction.' },
    ],
    metaTitle: 'PDF to Word Converter - Free Online PDF to Word Conversion',
    metaDescription: 'Convert PDF to Word online for free. Extract text from PDF files. Fast PDF to Word converter. No signup required.',
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert text/Word content to PDF online for free.',
    icon: '📄',
    route: '/tools/word-to-pdf',
    category: 'pdf',
    keywords: ['word to pdf converter', 'convert word to pdf free', 'doc to pdf online'],
    relatedTools: ['pdf-to-word', 'pdf-compressor', 'pdf-merge'],
    faq: [
      { question: 'What input formats are supported?', answer: 'You can paste text or HTML content to convert to PDF.' },
      { question: 'Will formatting be preserved?', answer: 'Basic text formatting is preserved. Complex layouts may vary.' },
      { question: 'Is there a size limit?', answer: 'No size limit for text-based conversions.' },
      { question: 'Is the conversion free?', answer: 'Yes, completely free with no watermarks.' },
    ],
    metaTitle: 'Word to PDF Converter - Free Online Word to PDF Conversion',
    metaDescription: 'Convert Word to PDF online for free. Create PDF from text content. Fast, free Word to PDF converter. No signup required.',
  },
  {
    id: 'pdf-merge',
    name: 'PDF Merge',
    description: 'Merge multiple PDF files into one online for free. Combine PDFs easily.',
    icon: '🔗',
    route: '/tools/pdf-merge',
    category: 'pdf',
    keywords: ['merge pdf online', 'combine pdf files free', 'pdf merger', 'join pdf files'],
    relatedTools: ['pdf-split', 'pdf-compressor', 'pdf-to-jpg'],
    faq: [
      { question: 'How many PDFs can I merge?', answer: 'You can merge multiple PDF files at once.' },
      { question: 'Is the order preserved?', answer: 'Yes, PDFs are merged in the order you upload them. You can reorder before merging.' },
      { question: 'Is there a file size limit?', answer: 'Each file can be up to 50MB. Total merged size may vary.' },
      { question: 'Are my PDFs secure?', answer: 'Yes, all processing happens in your browser. Files are never uploaded to servers.' },
    ],
    metaTitle: 'Merge PDF Online Free - Combine PDF Files | PDF Merger Tool',
    metaDescription: 'Merge PDF files online for free. Combine multiple PDFs into one document. Fast, secure PDF merger. No signup, no watermarks.',
  },
  {
    id: 'pdf-split',
    name: 'PDF Split',
    description: 'Split PDF into multiple files online for free. Extract pages from PDF.',
    icon: '✂️',
    route: '/tools/pdf-split',
    category: 'pdf',
    keywords: ['split pdf online', 'pdf splitter free', 'extract pages from pdf', 'divide pdf'],
    relatedTools: ['pdf-merge', 'pdf-compressor', 'pdf-to-jpg'],
    faq: [
      { question: 'How do I split a PDF?', answer: 'Upload your PDF, specify page ranges, and click Split to download separate files.' },
      { question: 'Can I extract specific pages?', answer: 'Yes, you can specify any page range like "1-3, 5, 7-10".' },
      { question: 'What is the output format?', answer: 'Each split section is saved as a separate PDF file.' },
      { question: 'Is there a page limit?', answer: 'No page limit for splitting PDFs.' },
    ],
    metaTitle: 'Split PDF Online Free - Extract Pages from PDF | PDF Splitter',
    metaDescription: 'Split PDF files online for free. Extract specific pages from PDF. Fast, free PDF splitter tool. No signup required.',
  },
  {
    id: 'pdf-compressor',
    name: 'PDF Compressor',
    description: 'Compress PDF files online for free. Reduce PDF file size.',
    icon: '🗜️',
    route: '/tools/pdf-compressor',
    category: 'pdf',
    keywords: ['compress pdf online', 'pdf compressor free', 'reduce pdf size', 'pdf optimizer'],
    relatedTools: ['pdf-merge', 'pdf-split', 'pdf-to-jpg'],
    faq: [
      { question: 'How much can PDF be compressed?', answer: 'Compression varies by content. Text-heavy PDFs compress well; image-heavy PDFs may compress less.' },
      { question: 'Will compression affect quality?', answer: 'Minimal quality impact. The tool optimizes PDF structure without visible quality loss.' },
      { question: 'What is the maximum file size?', answer: 'You can compress PDFs up to 50MB.' },
      { question: 'Is compression lossless?', answer: 'Our tool uses lossless compression techniques to reduce file size.' },
    ],
    metaTitle: 'Compress PDF Online Free - Reduce PDF File Size | PDF Compressor',
    metaDescription: 'Compress PDF files online for free. Reduce PDF size without quality loss. Fast, free PDF compressor. No signup required.',
  },
  {
    id: 'pdf-lock',
    name: 'PDF Lock',
    description: 'Password protect PDF files online for free. Secure your PDF documents.',
    icon: '🔒',
    route: '/tools/pdf-lock',
    category: 'pdf',
    keywords: ['password protect pdf', 'lock pdf online', 'pdf password protection', 'secure pdf'],
    relatedTools: ['pdf-unlock', 'pdf-merge', 'pdf-watermark'],
    faq: [
      { question: 'How secure is PDF password protection?', answer: 'This tool adds basic password metadata to the PDF. For high-security needs, use dedicated encryption software.' },
      { question: 'Can I set different passwords?', answer: 'You can set a user password to restrict opening the document.' },
      { question: 'What if I forget the password?', answer: 'There is no way to recover a forgotten password. Keep your password safe.' },
      { question: 'Is this encryption strong?', answer: 'This provides basic protection. For sensitive documents, use professional encryption tools.' },
    ],
    metaTitle: 'PDF Lock - Password Protect PDF Online Free | Secure PDF',
    metaDescription: 'Password protect PDF files online for free. Lock PDF documents with a password. Secure your PDFs. No signup required.',
  },
  {
    id: 'pdf-unlock',
    name: 'PDF Unlock',
    description: 'Remove PDF password protection online for free. Unlock PDF documents.',
    icon: '🔓',
    route: '/tools/pdf-unlock',
    category: 'pdf',
    keywords: ['unlock pdf online', 'remove pdf password', 'pdf unlocker free', 'decrypt pdf'],
    relatedTools: ['pdf-lock', 'pdf-merge', 'pdf-compressor'],
    faq: [
      { question: 'Can I unlock any PDF?', answer: 'You can unlock PDFs where you know the password. We cannot bypass unknown passwords.' },
      { question: 'Is unlocking PDFs legal?', answer: 'Only unlock PDFs you own or have permission to access.' },
      { question: 'What happens to the password?', answer: 'The password is used locally in your browser and never stored or transmitted.' },
      { question: 'Is this tool free?', answer: 'Yes, completely free.' },
    ],
    metaTitle: 'PDF Unlock - Remove PDF Password Online Free | PDF Unlocker',
    metaDescription: 'Remove PDF password protection online for free. Unlock PDF documents. Fast, free PDF unlocker. No signup required.',
  },
  {
    id: 'pdf-watermark',
    name: 'Add Watermark to PDF',
    description: 'Add text watermark to PDF online for free. Protect your PDF documents.',
    icon: '💧',
    route: '/tools/pdf-watermark',
    category: 'pdf',
    keywords: ['add watermark to pdf', 'pdf watermark online', 'watermark pdf free', 'stamp pdf'],
    relatedTools: ['pdf-lock', 'pdf-page-numbers', 'pdf-merge'],
    faq: [
      { question: 'Can I customize the watermark?', answer: 'Yes, you can set the text, size, opacity, and position of the watermark.' },
      { question: 'Is the watermark on all pages?', answer: 'Yes, the watermark is applied to all pages of the PDF.' },
      { question: 'Can I add an image watermark?', answer: 'Currently, only text watermarks are supported.' },
      { question: 'Can the watermark be removed?', answer: 'The watermark is embedded in the PDF and cannot be easily removed.' },
    ],
    metaTitle: 'Add Watermark to PDF Online Free - PDF Watermark Tool',
    metaDescription: 'Add text watermark to PDF files online for free. Customize watermark text, size, and opacity. Fast, free PDF watermark tool.',
  },
  {
    id: 'pdf-page-numbers',
    name: 'PDF Page Numbers',
    description: 'Add page numbers to PDF online for free. Number PDF pages automatically.',
    icon: '🔢',
    route: '/tools/pdf-page-numbers',
    category: 'pdf',
    keywords: ['add page numbers to pdf', 'pdf page numbering', 'number pdf pages', 'pdf pagination'],
    relatedTools: ['pdf-watermark', 'pdf-merge', 'pdf-split'],
    faq: [
      { question: 'Where are page numbers added?', answer: 'You can choose to add page numbers at the top or bottom of each page.' },
      { question: 'Can I customize the format?', answer: 'Yes, you can choose the starting number and position.' },
      { question: 'Are page numbers added to all pages?', answer: 'Yes, page numbers are added to every page of the PDF.' },
      { question: 'Is this tool free?', answer: 'Yes, completely free with no watermarks.' },
    ],
    metaTitle: 'Add Page Numbers to PDF Online Free - PDF Page Numbering Tool',
    metaDescription: 'Add page numbers to PDF files online for free. Automatically number PDF pages. Choose position and format. Fast, free tool.',
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Convert PDF pages to JPG images online for free. Extract images from PDF.',
    icon: '🖼️',
    route: '/tools/pdf-to-jpg',
    category: 'pdf',
    keywords: ['pdf to jpg converter', 'convert pdf to image free', 'pdf to jpeg online', 'extract images from pdf'],
    relatedTools: ['jpg-to-pdf', 'pdf-compressor', 'image-compressor'],
    faq: [
      { question: 'How many pages can I convert?', answer: 'You can convert all pages of a PDF to individual JPG images.' },
      { question: 'What resolution are the images?', answer: 'Images are rendered at 150 DPI by default for good quality.' },
      { question: 'Can I choose which pages to convert?', answer: 'Currently all pages are converted. You can then use individual images as needed.' },
      { question: 'Is there a file size limit?', answer: 'PDFs up to 50MB can be converted.' },
    ],
    metaTitle: 'PDF to JPG Converter - Free Online PDF to Image Conversion',
    metaDescription: 'Convert PDF to JPG images online for free. Extract pages from PDF as JPG images. Fast, free PDF to image converter.',
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Convert JPG images to PDF online for free. Create PDF from images.',
    icon: '📋',
    route: '/tools/jpg-to-pdf',
    category: 'pdf',
    keywords: ['jpg to pdf converter', 'convert image to pdf free', 'jpeg to pdf online', 'images to pdf'],
    relatedTools: ['pdf-to-jpg', 'pdf-merge', 'image-compressor'],
    faq: [
      { question: 'Can I add multiple images?', answer: 'Yes, you can add multiple JPG images and they will be combined into a single PDF.' },
      { question: 'What image formats are supported?', answer: 'JPG, PNG, WebP, and most common image formats.' },
      { question: 'Can I reorder images?', answer: 'Yes, you can reorder images before converting to PDF.' },
      { question: 'Is there a limit on images?', answer: 'You can add up to 20 images per conversion.' },
    ],
    metaTitle: 'JPG to PDF Converter - Free Online Image to PDF Conversion',
    metaDescription: 'Convert JPG images to PDF online for free. Combine multiple images into one PDF. Fast, free JPG to PDF converter.',
  },
];

export const allTools: ToolData[] = [...imageTools, ...pdfTools];

export function getToolById(id: string): ToolData | undefined {
  return allTools.find(t => t.id === id);
}

export function getRelatedTools(toolId: string): ToolData[] {
  const tool = getToolById(toolId);
  if (!tool) return [];
  return tool.relatedTools.map(id => getToolById(id)).filter(Boolean) as ToolData[];
}
