/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BlogPost = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'relatedTools' : IDL.Vec(IDL.Text),
  'date' : IDL.Text,
  'author' : IDL.Text,
  'category' : IDL.Text,
});
export const ToolUsage = IDL.Record({
  'usageCount' : IDL.Nat,
  'toolName' : IDL.Text,
});
export const DailyAnalytics = IDL.Record({
  'date' : IDL.Text,
  'visitorCount' : IDL.Nat,
  'toolUsage' : IDL.Vec(ToolUsage),
});

export const idlService = IDL.Service({
  'addBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'addContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getBlogPostsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BlogPost)],
      ['query'],
    ),
  'getBlogPostsSortedByDate' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getDailyAnalytics' : IDL.Func([IDL.Text], [DailyAnalytics], ['query']),
  'updateAnalytics' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BlogPost = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'relatedTools' : IDL.Vec(IDL.Text),
    'date' : IDL.Text,
    'author' : IDL.Text,
    'category' : IDL.Text,
  });
  const ToolUsage = IDL.Record({
    'usageCount' : IDL.Nat,
    'toolName' : IDL.Text,
  });
  const DailyAnalytics = IDL.Record({
    'date' : IDL.Text,
    'visitorCount' : IDL.Nat,
    'toolUsage' : IDL.Vec(ToolUsage),
  });
  
  return IDL.Service({
    'addBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'addContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getBlogPostsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BlogPost)],
        ['query'],
      ),
    'getBlogPostsSortedByDate' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getDailyAnalytics' : IDL.Func([IDL.Text], [DailyAnalytics], ['query']),
    'updateAnalytics' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };