/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'title' : string,
  'content' : string,
  'relatedTools' : Array<string>,
  'date' : string,
  'author' : string,
  'category' : string,
}
export interface DailyAnalytics {
  'date' : string,
  'visitorCount' : bigint,
  'toolUsage' : Array<ToolUsage>,
}
export interface ToolUsage { 'usageCount' : bigint, 'toolName' : string }
export interface _SERVICE {
  'addBlogPost' : ActorMethod<
    [string, string, string, string, string, Array<string>],
    undefined
  >,
  'addContactMessage' : ActorMethod<[string, string, string], undefined>,
  'getBlogPostsByCategory' : ActorMethod<[string], Array<BlogPost>>,
  'getBlogPostsSortedByDate' : ActorMethod<[], Array<BlogPost>>,
  'getDailyAnalytics' : ActorMethod<[string], DailyAnalytics>,
  'updateAnalytics' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];